name: 'get-next-event'
description: 'return the summary, description, start, and end datetimes for the next instance of a public iCal event'
inputs:
  ical-address: 
    description: 'URL to a public iCal destination'
    required: true
  event-name: 
    description: 'summary (title) of the event'
    required: true
  lookout-days: 
    description: 'number of days to look forward'
    required: true
    default: '365'
outputs:
  summary:
    description: 'event title or summary'
  description: 
    description: 'event description'
  start:
    description: 'event start datetime'
  end:
    description: 'event end datetime'
runs:
  using: 'node12'
  main: 'index.js'