# This is a basic workflow to help you get started with Actions

name: ical-event-detector

on: [push]

jobs:
  get_next_event:
    runs-on: ubuntu-latest
    name: iCal Event Detector
    steps:
      - name: run ical from public repo
        uses: andyschwab/action-ical-event@v1
        id: icalevent
        with:
          ical-address: "https://calendar.google.com/calendar/ical/ipfs.io_eal36ugu5e75s207gfjcu0ae84@group.calendar.google.com/public/basic.ics"
          event-summary: "IPFS Weekly Call"
          lookout-days: 7
      - name: test ical response
        run: echo 'Summary - ${{ steps.icalevent.outputs.summary }}'
        run: echo 'Description - ${{ steps.icalevent.outputs.description }}'
        run: echo 'Start - ${{ steps.icalevent.outputs.start }}'
        run: echo 'End - ${{ steps.icalevent.outputs.end }}'
