# This is a basic workflow to help you get started with Actions

name: ical-event-detector

on: [push]

jobs:
  get_next_event:
    runs-on: ubuntu-latest
    name: Get Next iCal Event
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run
        uses: ./
        id: icalevent
        with:
          ical-address: "https://calendar.google.com/calendar/ical/ipfs.io_eal36ugu5e75s207gfjcu0ae84@group.calendar.google.com/public/basic.ics"
          event-name: "IPFS Weekly Call"
          lookout-days: 30
      - name: Test Response
        run: echo 'Recieved ${{ steps.icalevent.outputs.start }}'
