# This is a basic workflow to help you get started with Actions

name: iCalEventDetector

on: [push]

jobs:
  get_next_event:
    runs-on: ubuntu-latest
    name: Get Next iCal Event
    steps:
      # To use this repository's private action, you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Install dependencies
        run: npm install
      - name: Run iCalEventDetector
        uses: ./
        id: icalevent
        with:
          ical-address: "https://calendar.google.com/calendar/ical/ipfs.io_eal36ugu5e75s207gfjcu0ae84@group.calendar.google.com/public/basic.ics"
          event-name: "IPFS Weekly Call"
          lookout-days: 30
      # Use the output from the `hello` step
      - name: Test response
        run: echo "Recieved ${{ steps.icalevent.outputs.summary }}"
